### ISSUE TITLE
Améliorations à apporter dans les graphiques

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#107]
1. CV_LV / Courbe de variation des jours ouvrables (du lundi au vendredi) 
 - nombres sans décimale sur l'axe vertical
 - légende basée sur les cellules data_day / A3; A33; A64
2. SWISSxx_G
 - Ajouter "du TJM" à la fin de la légende de l'axe vertical

Résultats dans le fichier ci-joint
[00056520_20180924_r.xlsx](https://github.com/opengisch/OpenComptage/files/3691284/00056520_20180924_r.xlsx)

**Comment by marioba** [comment]
> légende basée sur les cellules data_day / A3; A33; A64

La légende est basées sur les cellules k4, k34 et k65

> Ajouter "du TJM" à la fin de la légende de l'axe vertical

OK, fait

**Comment by spch-GL** [comment]
Si j'ai bien compris, ce point est aussi terminé :-)
