### ISSUE TITLE
Attribute table actions are not always visible

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#112]
Par ailleurs, il y a un petit souci avec la fenêtre table d’attributs
![image](https://user-images.githubusercontent.com/24844357/70078906-efac9780-1603-11ea-9c9e-bd9d4c6b58e4.png)

Si je veux trier par l’une ou l’autre colonne, cela cache la colonne ID avec les actions :
![image](https://user-images.githubusercontent.com/24844357/70078941-fa672c80-1603-11ea-9d41-3939ddf69f0f.png)

**Comment by spch-GL** [comment]
> Attribute table **ID's** are not always visible

**Comment by marioba** [comment]
Il semble que ce soit un bug QGIS. Je l'ai signalé ici https://github.com/qgis/QGIS/issues/33464

**Comment by spch-GL** [comment]
testé ok dans 3.10.12 et 3.16.1
