### ISSUE TITLE
extension desactivee

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#120]
Au lancement de la version 3.10.9 (Windows10): 
`2020-08-24T14:15:03     WARNING    Extension comptages : Cette extension sera désactivée car elle a entraîné un plantage de QGIS lors du dernier démarrage. Merci de faire remonter le problème et de réactiver l'extension lorsque ce dernier aura été réglé.`
Il semble que cela fonctionne mieux avec la 3.14.15, car il n'y a pas de message au démarrage

**Comment by marioba** [comment]
L'extension a été désactivée parce qu'elle était bloquée. Est-ce quelque chose qui arrive tout le temps avec QGIS 3.10 ou est-ce arrivé une seule fois ? 
Parce que si c'est quelque chose qui n'est arrivé qu'une seule fois, la réactivation du plugin dans le plugin manager devrait tout régler.

S'il s'agit d'un problème qui se produit chaque fois avec il faut enquêter pour en trouver la cause.

**Comment by spch-GL** [comment]
cela ne se produit plus non plus avec la 3.16.1
