### ISSUE TITLE
import data may overflow database server

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#140]
Lors de l'importation de 723 fichiers (1 année de comptages) le serveur ne répondait plus correctement et il a fallu fermer ~200 connexions. L'importation n'a donc pas réussi.

Il y a apparemment une connexion par insert. Il faudrait limiter le nombre de connexions simultanées à une dizaine

Le SITN demande aussi si les connexions sont bien refermées après usage ?

**Comment by marioba** [comment]
Thanks for the suggestion. The part about data writing to the database will be completely revised and improved soon for the new version of the plugin
