### ISSUE TITLE
Calculate LPSEPS in config file

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#143]
To be used in the configuration file. Currently is not present in the DB.

Should be calculated based on the data from the `sensor` table. If no data is present for the used sensor, a default value is to be used.

(btw LPLENS is always 200)

Related to #51

**Comment by marioba** [comment]
Si le segment mesure plus de 6 m, LPSEPS=500 sinon il vaut 300

**Comment by spch-GL** [comment]
Oui, et la valeur par défaut est LPSEPS=500

**Comment by marioba** [comment]
Donc:
LPSEPS=500. If segment geometry length < 6m -> LPSEPS=300

Correct @spch-GL ?

**Comment by spch-GL** [comment]
Exact, mais If segment geometry length < 6m -> LPSEPS=300 va aussi
