### ISSUE TITLE
Consider direction 0/1 as 1/2

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#177]
Comme convenu lors de notre dernière discussion, je viens de discuter avec Cédric et peut confirmer que 0-1 devient toujours 1-2 dans cet ordre.

 Il faut donc prévoir une manipulation automatique pour transformer les direction 0-1 en 1-2 durant le traitement.

**Comment by spch-GL** [comment]
voici le fichier :)
[00107600_Clusette_Brot-Dsous.zip](https://github.com/opengisch/OpenComptage/files/9021059/00107600_Clusette_Brot-Dsous.zip)

**Comment by marioba** [comment]
Peux-tu vérifier le résultat de cette query ?

```sql
select * from comptages.lane where id_section = '00107600';
```

**Comment by spch-GL** [comment]
cela me donne:
406	1	1	"La Nantillière (Rochefort)[H10]"	202	"00107600"
407	2	1	"La Nantillière (Rochefort)[H10]"	202	"00107600"
408	3	2	"Bas de la Clusette [H10]"	202	"00107600"

**Comment by spch-GL** [comment]
en image:
![image](https://user-images.githubusercontent.com/26377323/176830791-7a9e48e0-f1a1-40bc-b8cf-ac925fff5fad.png)

**Comment by marioba** [comment]
Le tronçon a donc 3 voies. Je pense que maintenant, lorsque vous importez le fichier, les données ne sont mises que sur les 2 premières voies de cette facon:

| `dir` field in data file | lane |
|---|---|
| 0 | 406 |
| 1 | 407 |

Si le fichier indique la direction 0, comment le système doit-il procéder pour déterminer à laquelle des deux premières vois (406 ou 407) il se réfère ?

**Comment by spch-GL** [comment]
il doit mettre les "1" sur la lane qui a la direction 2
et les "0" sur une lane qui a la direction 1

Il n'est pas possible de différencier  la voie avec des tubes, seulement avec des boucles ou des piézos
