### ISSUE TITLE
Date problem in TJM graphs

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#183]
Start process date seems to be correct (should begin at 0:00:00.0) but End process date should end at 23:59:59.99999)
example:
![image](https://user-images.githubusercontent.com/26377323/138257807-f3e8cd54-8ad2-4a79-977d-1bbac4fb5ca0.png)
![image](https://user-images.githubusercontent.com/26377323/138257855-1ec845f6-b278-4758-a77c-3c3907497ac3.png)

**Comment by spch-GL** [comment]
Salut Mario,
Avec la V0.10, ça recommence...

**Comment by spch-GL** [comment]
En fait cela affecte aussi sur les graphes "par heure"

**Comment by marioba** [comment]
Yes, I know. It will be fixed as soon as I merge the report branch on which I'm currently working on.
