### ISSUE TITLE
Comment mettre à jour nos bases de données ? 

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#206]
Il y a en tous cas la table TJM à recalculer, y en a-t-il d'autres ?

**Comment by spch-GL** [comment]
La structure a changé, ce n'est donc plus la table à recalculer mais le champs TJM de la table count... Ca semble fonctionner avec le script fourni tjmreset. 
Mais il y a encore au moins une mise à jour à passer sur nos bases: le champs timestamp de la table count_detail est désormais défini comme `timestamp with time zone`. Comment faire pour changer cela sans perturber les données ?

**Comment by marioba** [comment]
First of all you should verify that the timezone configured in the database is `Europe/Zurich` or a equivalent one.

```sql
SHOW timezone;
-- Europe/Zurich
```

If so you can change the column type with:

```sql
ALTER TABLE comptages.count_detail 
  ALTER COLUMN timestamp
  SET DATA TYPE timestamp with time zone;

```

**Comment by spch-GL** [comment]
La correction génère une erreur:
```
ERROR: ERREUR:  ne peut pas modifier le type d'une colonne utilisée dans une vue ou une règle
DETAIL:  règle _RETURN sur vue matérialisée v_count_swiss7 dépend de la colonne « timestamp »


SQL state: 0A000
```

**Comment by maltaesousa** [comment]
C'est ma faute, j'ai supprimé les vues matérialisées en question. Peux-tu ressayer @spch-GL ?

**Comment by spch-GL** [comment]
Cette fois la commande est passée correctement, merci Stéphane
