### ISSUE TITLE
Crash à l'importation SWISS10

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#207]
## User Feedback

Importation de 18 jours en SWISS10 dans Comptages 0.9.15
[00056520.zip](https://github.com/opengisch/OpenComptage/files/7481336/00056520.zip)

Après réouverture de QGIS, il n'y a pas de données pour ce comptage:
2021-11-05T08:32:05     INFO    Comptages : Installation 00056520: Il n'y a pas de données à montrer pour le comptage 2
Mais il y a des données à valider:
![image](https://user-images.githubusercontent.com/26377323/140476411-3dd2bf3c-f530-4879-8a5d-9baf3e3edd4e.png)

## Report Details

**Crash ID**: [08eb046d70c686f4b758980ac9d4b7cab11fed54](https://github.com/qgis/QGIS/search?q=08eb046d70c686f4b758980ac9d4b7cab11fed54&type=Issues)

**Stack Trace**
<pre>
QMutex::lock :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

</pre>

**QGIS Info**
QGIS Version: 3.22.0-Bia?owie?a
QGIS code revision: d9022691f1
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.2
Running against GDAL: 3.3.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by spch-GL** [comment]
J'ai alors refusé les données pour importer un seul fichier (A) et cela a fonctionné, mais il y avait les graphes pour 2 jours (je pense que c'est dû au décalage horaire...)

Je n'ai pas accepté ni refusé les données, mais fermé la fenêtre des graphiques. Puis j'ai importé un second jour (B), mais là les graphiques n'ont pas été afficher après plus d'une minute. J'ai alors cliqué sur la barre de progression affichant 100%, et re Crash QGIS
![image](https://user-images.githubusercontent.com/26377323/140477929-6b7a2c93-052f-4928-9ef5-999d8afbd226.png)
Après redémarrage de QGIS, il y a maintenant les données suivantes dans le graphe de validation:
![image](https://user-images.githubusercontent.com/26377323/140478349-fec15c12-b7df-4639-b33a-ab598bb5add8.png)

**Comment by spch-GL** [comment]
Encore une info.
Lors de l'importation d'un seul fichier, QGIS crash aussi, mais seulement après qu'on l'aie fermé

**Comment by marioba** [comment]
For into I attached a video of what this import looks on my computer.
[Peek 2021-11-06 08-37.zip](https://github.com/opengisch/OpenComptage/files/7490255/Peek.2021-11-06.08-37.zip)

Probably the cause is the same discussed on #205

**Comment by spch-GL** [comment]
Avec la version 0.9.18, il n'y a plus de crash et l'import fonctionne. Mais j'ai en tout cas deux petites différences dans la fenêtre du graphique: 
![image](https://user-images.githubusercontent.com/26377323/140728082-0f84af06-3328-46c9-954d-9e7901d022d2.png)

**Comment by marioba** [comment]
Should be fixed in v0.10.0
