### ISSUE TITLE
development version: cannot initialize datamodel

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#216]
There is a problem with DJANGO:
File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\conf\__init__.py", line 63, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by marioba** [comment]
What do you mean with development version?

**Comment by spch-GL** [comment]
Salut Mario,
J'essaie d'installer la BD selon la doc. Mais j'ai trouvé:
en mettant à jour ainsi (après `pip install -r requirements.txt`)
`pip install --upgrade icalendar nose2 wheel openpyxl psycopg2 django qdmtk==0.0.1a2`
Cela fonctionne :)
