### ISSUE TITLE
problème de rapport avec classe SPCH-13

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#219]
Dans la version 0.10.2, avec ce fichier
[21703675-Fenin675.txt](https://github.com/opengisch/OpenComptage/files/7556480/21703675-Fenin675.txt)

Les graphes semblent correctes:
![image](https://user-images.githubusercontent.com/26377323/142245816-522ce8ec-3dd8-4c2a-9393-b01833d400db.png)

Mais le rapport ne regroupe pas les classes correctement; 
[21703675_20200608_r.xlsx](https://github.com/opengisch/OpenComptage/files/7556494/21703675_20200608_r.xlsx)
[21703675_20200615_r.xlsx](https://github.com/opengisch/OpenComptage/files/7556496/21703675_20200615_r.xlsx)

Dans le rapport, il semble que ce qui est dans CAR devrait être dans MR, ce qui est dans MR devrait être dans PW et ce qui est dans PW devrait être dans CAR

**Comment by marioba** [comment]
To be sure, this table (`FHWA13 --> SWISS7`) is also used to convert `SPCH-13 --> SWISS7`?

![image](https://user-images.githubusercontent.com/24844357/142568633-0f6a46d6-1590-40b2-b8f5-7e643ece55dc.png)

**Comment by spch-GL** [comment]
exact, avec le model de compteur MC5900

**Comment by marioba** [comment]
Est-ce le seul modèle utilisé pour mesurer SPCH-13 ?

**Comment by spch-GL** [comment]
Oui, en tous cas pour l'instant... mais nous n'avons pas prévu d'acheter d'autres modèles à court terme

**Comment by marioba** [comment]
Should be fixed

**Comment by spch-GL** [comment]
Dans ce cas nous avons un souci...
Exemple, après import de ce fichier: 
[00107835_Ecluse-St-Nicolas.txt](https://github.com/opengisch/OpenComptage/files/7640884/00107835_Ecluse-St-Nicolas.txt)

les graphiques semblent corrects (10.3% de bus):
![image](https://user-images.githubusercontent.com/26377323/144401174-d443b266-16e5-45d1-920f-2355a4702c93.png)

Mais le rapport ne fournit pas les bus dans la classe 1:
![image](https://user-images.githubusercontent.com/26377323/144401931-87082725-3044-4100-8d81-94d9c1609366.png)

voici le rapport complet:
[00107835_20201102_r.xlsx](https://github.com/opengisch/OpenComptage/files/7641032/00107835_20201102_r.xlsx)

Si cela peut provenir des données (class, class_category, category), quelles vérifications/corrections dois-je y effectuer ?

**Comment by spch-GL** [comment]
En fait, il y a un souci avec la table de conversion ou la classe SPCH-13...
La requête 
```
SELECT * FROM comptages.category where id in (
	SELECT id_category FROM comptages.class_category WHERE id_class = (
		SELECT id FROM comptages.class WHERE name='SPCH-13'
	) 
)
```
retourne
![image](https://user-images.githubusercontent.com/26377323/144406527-15284629-9971-4c7a-8c46-8d087359ed88.png)

Les bus ont donc le code 4 dans la classe, mais 7 dans la table de conversion...

**Comment by spch-GL** [comment]
J'ai demandé à Jonathan et Cédric ce qu'il fallait changer.

**Comment by marioba** [comment]
![image](https://user-images.githubusercontent.com/24844357/149451353-0f71fbf8-4cb5-4f5c-9544-070fee2df42e.png)
