### ISSUE TITLE
uniformisation des onglets du rapport hebdomadaire

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#221]
Pour les onglets Data_day, Data_speed et Data_category, je propose de toujours commencer par la direction 1, puis la direction 2.
A mon avis, dans Data_day, la section est une somme de ces 2 directions donc pas besoin de la calculer dans le plugin (on gagnera peut-être un peu en rapidité).
Dans le code ci joint, sur la base de la 0.10.2, j'ai aussi 

- ajouté quelques infos dans les logs
- changé l'ordre des couches et ajouté sensor, mais je n'ai pas trouvé comment mettre extra tout à la fin
- modifié la symbologie pour ma base de dev (pas utile pour la prod)
[_param_GL.zip](https://github.com/opengisch/OpenComptage/files/7568346/_param_GL.zip)

**Comment by marioba** [comment]
Merci, mais ne serait-il pas possible pour toi de faire une Pull Request avec tes modifications ?

**Comment by spch-GL** [comment]
Oui, sûrement, mais je n'ai plus fais cela depuis un certain temps et ne me rappelle plus la procédure à suivre...
