### ISSUE TITLE
Incohérence entre les données de la base et le graphique

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#236]
Lors de l'importation de ce fichier (
[00107835_Ecluse-318.txt](https://github.com/opengisch/OpenComptage/files/7863921/00107835_Ecluse-318.txt)
) 
le plugin (0.10.3 ou 0.10.4) affiche:
![image](https://user-images.githubusercontent.com/26377323/149362422-fa0d1c42-739a-45c0-9dae-ddfd62ba9ee1.png)

Mais ces pourcentages ne correspondent pas exactement aux véhicules qui figurent dans la base:
![image](https://user-images.githubusercontent.com/26377323/149361242-602807d4-8824-4a8b-8eec-d413512c0410.png)

Démo:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GrelletP/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GrelletP/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

id_category | nb_veh | % Base | % Graph
-- | -- | -- | --
103 | 2880 | 7.8344% | 8.0700%
104 | 29126 | 79.2307% | 78.5000%
105 | 11 | 0.0299% | 0.0341%
106 | 1118 | 3.0413% | 3.2700%
107 | 16 | 0.0435% | 0.0477%
108 | 5 | 0.0136% | 0.0136%
109 | 3379 | 9.1918% | 9.4200%
110 | 145 | 0.3944% | 0.4360%
112 | 56 | 0.1523% | 0.1600%
113 | 16 | 0.0435% | 0.0477%
115 | 9 | 0.0245% | 0.0136%

</body>

</html>

![image](https://user-images.githubusercontent.com/26377323/149363083-f99e4e9e-5ba1-4926-9dc3-f05a1041628f.png)

**Comment by marioba** [comment]
I have exactly the same numbers in the database
![image](https://user-images.githubusercontent.com/24844357/149458664-5c77755d-b612-41e0-bd63-dee0c082b86f.png)

And the chart shows the correct numbers...
![image](https://user-images.githubusercontent.com/24844357/149458791-656d2851-4c17-4196-a44a-2b5f881d2f54.png)

Can you please try with version (v0.10.5)? (The last version also shows the numbers in the category chart so we can maybe understand what happens)

**Comment by spch-GL** [comment]
Sans modifier mon comptage, donc avec la même BD que hier, mais en mettant à jour le plugin en 0.10.5, le graphique n'est pas bon :-(
![image](https://user-images.githubusercontent.com/26377323/149496442-467d1ef5-dd1f-423a-9a04-a2b12eb0f85d.png)

**Comment by marioba** [comment]
Les dates "début traitement" et "fin traitement" que tu as mis ne comprennent pas toutes les données du comptage (et qui sont importées).
