### ISSUE TITLE
Always show validation buttons when new data is in the count

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#240]
Suite au problème de graphique, j'ai maintenant 2 comptages à valider, le 7 et le 8, mais lorsque je clique sur "Validation" il n' y a que le comptage 7 qui est présenté:
![image](https://user-images.githubusercontent.com/26377323/149499161-48f643ce-fa3c-4d98-a058-69d6fbe5354c.png)

**Comment by spch-GL** [comment]
Mario,
Est-ce que cela peut provenir du dossier qgissettingmanager ?
Car, je l’ai récupéré d’une ancienne version…

Pierre Grellet
Chef de projets en informatique technique

**Comment by marioba** [comment]
Ça n'a pas toujours été comme ça ? 

Seulement pour les cas spéciaux, il y a plusieurs onglets (un par tronçon).
