### ISSUE TITLE
Date range in charts

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#241]
This will add two date widgets and a button in the chart dialog to filter the data. Something like this:
![image](https://user-images.githubusercontent.com/24844357/152534114-dd88678f-8f0b-49ac-acdc-4841caff8371.png)

The range in the calendar widgets is limited to the "service period" of the count.

**Comment by marioba** [comment]
J'ai implémenté la fonctionnalité discutée lors de la dernière réunion concernant la "Date Range" dans les graphiques. Cependant, il reste un détail à éclaircir.

Il a été décidé que les données entre "Début traitement" et "Fin traitement" seraient présentées dans le graphique par défaut.

Étant donné que lorsque l'on appuie sur "Valider" ou "Réfuser", seules les données visibles sont validées ou rejetées, il y a un risque que, après l'importation, si des données se trouvent en dehors de la période de "traitement", elles restent en attente, non validées mais non visibles dans le graphique par défaut.

Je vois quelques possibilités :
- limiter l'importation aux données qui sont dans la période de "traitement" (ce qui ne me semble pas être le cas actuellement).
- afficher initialement dans le graphique toutes les données du comptage, et pas seulement celles de la période de "traitement".
- après avoir appuyé sur "valider" ou "refuser", s'il n'y a plus de données à valider dans la période de "traitement", les autres sont automatiquement rejetées

**Comment by marioba** [comment]
@spch-GL
Y a-t-il des nouvelles sur ce point ?
Dès que j'aurai la réponse, je pourrai finaliser et publier les modifications de la version 2.1.

**Comment by spch-GL** [comment]
Nous aimerions 
- affichage de tous les jours de mesures 
- accepter une importation équivaut à purger les mesures hors traitement
Ce qui revient à accepter tes propositions sauf la première

**Comment by marioba** [comment]
Donc, pour résumer :
- lorsqu'un comptage est importé, tous les jours avec des mesures sont initialement affichés dans le graphique (pas seulement la période de "traitement").
- Lorsque le comptage est accepté, les jours figurant dans le graphique à ce moment-là sont définitivement importés et tous les autres sont écartés.

**Comment by spch-GL** [comment]
Presque:

- Lorsqu'un comptage est importé, tous les jours avec des mesures sont initialement affichés dans le graphique (pas seulement la période de "traitement"). (OK)
- Lorsque le comptage est accepté, **les jours de la période de "traitement" sont définitivement importés et tous les autres sont écartés**.
