### ISSUE TITLE
Cas spéciaux: comment définir l'ordre des voies ?

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#243]
Dans les fichiers à importer cet ordre est défini, mais comment OpenComtage détermine-t-il à quelle voie attribuer chaque canal ?

**Comment by marioba** [comment]
It uses the `number` field in the `lane` table.

**Comment by spch-GL** [comment]
Pourrais-tu compléter la doc au chapitre des **Cas spéciaux** ? 
et remplacer le select par (ajout de _l.number_ ): 
```
select l.id, l.number, l.id_section, l.id_installation, i."name"from lane as l
join installation as i
    on l.id_installation = i.id
    where i.name = '53409999'
```

Et ajouter un diagramme montrant toutes les relations que la table installation a avec les autres tables (en tout cas _count_ et _sensor_type_)
