### ISSUE TITLE
Municipality geometric intersection

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#245]
Get the name of the municipality determined by the intersection of the installation point with a new municipality layer.

**Comment by marioba** [comment]
@spch-GL The municipality is to be used in the reports? Sorry I don't remember.

**Comment by spch-GL** [comment]
C'est seulement pour la fiche de pose, selon moi

**Comment by maltaesousa** [comment]
@marioba just create a model that fulfill the needs for the app and we'll update the data based on a scheduled task.

The names and types of the colums in the provided excel are not mandatory. In other words, feel free to just use the columns you need. Take care, geom has to handle MultiPolygon.

**Comment by marioba** [comment]
@maltaesousa thanks, I created a simple model for the municipalities. The attached excel file appears to contain incomplete geometries, probably because the wkt fields were too long. Can you maybe try to create simple csv?

**Comment by spch-GL** [comment]
En l'absence de Stéphane, voici le CSV (séparé par des tab...) 
[Communes.csv](https://github.com/opengisch/OpenComptage/files/9446010/Communes.csv)

**Comment by marioba** [comment]
> En l'absence de Stéphane, voici le CSV (séparé par des tab...) [Communes.csv](https://github.com/opengisch/OpenComptage/files/9446010/Communes.csv)

Thanks
