### ISSUE TITLE
UUID default value is missing

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#248]
I don't understand why there is no default value defined in the tables statement for UUIDs... Could you add `DEFAULT uuid_generate_v4()` or would it broke somethng ?

**Comment by marioba** [comment]
Which table are you referring to?

**Comment by marioba** [comment]
This is due to the fact that uuid generation is done directly in Python by Django ORM. 

But it shouldn't create any problem to also add to the table in the database a default so that you can directly add elements from there.

**Comment by marioba** [comment]
Closed in version 0.10.12
