### ISSUE TITLE
Version 0.10.14: erreur au chargement

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#255]
Salut Mario,
Je n'arrive pas à installer cette version, voici le message d'erreur:
![image](https://user-images.githubusercontent.com/26377323/169530501-a8d9f54b-c7af-41d9-a3b3-c59217c7e529.png)

**Comment by marioba** [comment]
As tu installé la version 0.10.13? et ça a marché ?

**Comment by spch-GL** [comment]
oui, absolument, aucun souci avec la 0.10.13

**Comment by marioba** [comment]
Curieux. Il y a probablement eu un problème lors de la création chez vous du plugin que vous installez ou une erreur de QGIS lors de l'installation. 

Parce qu'entre la version 0.10.13 et la 0.10.14 seulement un test et une petite correction  dans une fonction utilisée pour générer les graphiques sont changé, et ces parties du code ne sont meme pas utilisée lors de l'installation du plugin.

Tu peut voir touts les changements ici https://github.com/opengisch/OpenComptage/compare/v0.10.13...v0.10.14

**Comment by spch-GL** [comment]
Oui, j'ai vu cela... je vais recréer le plug-in

**Comment by marioba** [comment]
il semble y avoir un problème avec le nom du plugin

**Comment by spch-GL** [comment]
Oui, pardon, j'avais changé le nom du dossier **comptages** en  **comptages_0.10.14_GL** !

**Comment by spch-GL** [comment]
C'est donc corrigé et fonctionnel :)
