### ISSUE TITLE
Limit fields options on create new count

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#43]
- Si boucles, alors ne proposer que les modèles et automates qui peuvent être utilisés avec des boucles,…
- Vérifier que l’automate n’est pas déjà posé (ou réservé),
- Pour la classification, proposer SWISS10 par défaut ou SWISS7 ou EURO13,… selon le modèle et automate choisis

**Comment by marioba** [comment]
I am analyzing a problem in QGIS that does not show the content of the value relation widgets if a filter expression is defined. Maybe a QGIS bug. At the moment it makes the form unusable if you filter the values.

**Comment by spch-GL** [comment]
As-tu pu avancer là-dessus ?
