### ISSUE TITLE
Improve config files

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#51]
Les fichiers de configuration ne sont pas encore complétement paramétrés en fonction des installations (CHANNELS, SENSORS, LPLENS, LPSEPS) et les paramétrages tirés de l’installation sont ajoutés à la fin du fichier, mais ne remplacent pas les paramétrages par défaut (SITE, LOCATION, FILENAME, CLASS)

**Comment by marioba** [comment]
See Pierre's email of 27.03.2019 - 16:59 and following

**Comment by spch-GL** [comment]
Cédric me dit que cela n'est pas encore tout à fait résolu. Notamment la distance entre les boucles est parfois erronnée

**Comment by spch-GL** [comment]
Lors de la création du fichier de commande (pour la pose d’un compteur à boucles), vérifier la table sensor pour le nombre de voies à compter et la distance entre les boucles (LPSEPS) 
Dans la table sensor, si il n'y a pas de segment relié à la voie, pour le tronçon considéré, ne pas compter cette voie
Si le segment mesure plus de 6 m, LPSEPS=500 sinon il vaut 300

**Comment by spch-GL** [comment]
Exemple pour voie à ne pas compter sur le tronçon 13201280. Il y a effectivement 3 voies, mais nous n'en comptons que 2 (la troisième est une présélection)

**Comment by marioba** [comment]
I close this because I created more detailed issues for these tasks (i.e. #144 )
