### ISSUE TITLE
Manage vehicles with 0 km/h speed

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#75]
From Pierre's email:

> Après réflexion, les véhicules dont la vitesse est de 0 km/h devraient aussi figurer dans la classe 0 (pour toutes les machines, pas seulement les MetroCount), mais peut-être l’as-tu déjà fait ?

> Par ailleurs les véhicules dont la vitesse est trop grande sont probablement aussi à mettre dans cette classe 0. Pour définir cette vitesse trop élevée je vois plusieurs moyens :

> 1.    Une constante dans le programme : 160km/h

> 2.    Une variable dans les réglages, plus souple mais pas idéal pour les cas spéciaux

> 3.    Une valeur fonction de la vitesse légale sur la voie comptée : max(150 ; 3*VitLeg). Je pense que nous avons une couche avec cette information

**Comment by jmaret287** [comment]
La solution 3 est désirée. Dans le fichier de config, la valeur VitLeg de la formule ci-dessus correspond à l'attribut "SPEEDLIMIT". 
Il faut donc que cet attribut qu'il soit récupéré automatiquement depuis la couche "vitesse" du SITN. Pierre fournira l'information pour aller chercher cette couche automatiquement. 
Si le poste de comptage se trouve sur un tronçon sans valeur dans la couche "vitesse", c'est donc la valeur 150 qui s'applique.
