### ISSUE TITLE
Some calculations are wrong

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#89]
Pour les formules, j’ai regardé 2 installations : 53309999 (Bevaix, EGA) et 00107695 (Corcelles, CTC)

 - EGA : je trouve les mêmes véhicules que toi (répartitions par jour de semaine, par vitesse, par classe) mais pas exactement les mêmes pourcentages PL, et surtout pas du tout les mêmes vitesses caractéristiques (plage AF23:AU75)

 - CTC : je trouve les mêmes véhicules que toi (répartitions par jour de semaine, par vitesse, par classe) mais pas exactement les mêmes pourcentages PL, et pas vraiment les mêmes vitesses caractéristiques (plage AF23:AU75)

**Comment by marioba** [comment]
I'm still working on this issue, because it's not entirely clear to me. From my tests it seems to me that my calculations respect what has been defined:

> V15 = vitesse du véhicule le plus rapide parmi les 15% de véhicules les plus lents
> V50 = vitesse du véhicule le plus rapide parmi les 50% de véhicules les plus lents
> V85 = vitesse du véhicule le plus rapide parmi les 85% de véhicules les plus lents

**Comment by spch-GL** [comment]
Concernant le %PL, j'ai trouvé:
Dans template.xlsx, il ne faut pas calculer la moyenne des %PL, mais le %PL des moyennes (par exemple en CV_H / J21)

**Comment by marioba** [comment]
Je calculais les vitesses caractéristiques de tous les véhicules du comptage et pas seulement de ceux de la période considérée.
