### ISSUE TITLE
Yearly report

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#92]
See Amiet Cédric's email of 24.06.2019 16:52

**Comment by marioba** [comment]
[Rapport_A-Modifier_annuel.pdf](https://github.com/opengisch/OpenComptage/files/4626781/Rapport_A-Modifier_annuel.pdf)

**Comment by jmaret287** [comment]
Pas de commentaire sur le document transmis. Y a t'il des questions ?
