### ISSUE TITLE
Manage FHWA13 category

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#93]
See Pierre's email 12.08.2019, 17:25

**Comment by marioba** [comment]
![image](https://user-images.githubusercontent.com/24844357/81908322-609ba680-95c9-11ea-86da-2ac9ea556b76.png)

**Comment by jmaret287** [comment]
Ce qui est attendu du point de vue métier : agrégation des données entrantes au format FHWA en donnée sortantes (et traitées) au format Swiss 7.
