### ISSUE TITLE
Create report's category page for ARX Cycle

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#94]

**Comment by marioba** [comment]
@spch-GL Quel doit être le contenu de la page ARX Cycle? As tu un example?

**Comment by spch-GL** [comment]
Bonne question, je n'ai pas encore d'exemple... je dois en demander un à Jonathan !

**Comment by jmaret287** [comment]
Jonathan et Cédric fourniront un exemple à la main du rapport mensuel désiré. 
Transmission à Mario pour le 6 janvier.

**Comment by marioba** [comment]
I close this because I continue on #148
