### ISSUE TITLE
Manage Marksmann devices data in a different way

### ISSUE THREAD

**Issue by marioba** [opengisch/OpenComptage#95]
En analysant ces rapports, nous nous sommes rendu compte que nos compteurs Marksmann ne produisait pas du SWISS7 correctement ! Peux-tu ajouter un test qui, lors de l’importation de données Swiss7 fournies par un compteur Marksmann, permute les classes selon le schéma suivant :

  | CS1 | CS2 | CS3 | CS4 | CS5 | CS6 | CS7
-- | -- | -- | -- | -- | -- | -- | --
SWISS7 Marksmann | PW (11) | CAR (1) | LIE (12) | LW (8) | LZ (9) | SZ (10) | MR (2)
SWISS7 officiel | CAR (1) | MR (2) | PW (11) | LIE (12) | LW (8) | LZ (9) | SZ (10)

**Comment by marioba** [comment]
@spch-GL peux-tu s.v.p. m'envoyer ou joindre ici un fichier d'exemple Marksmann avec la catégorie SWISS7 ?

**Comment by spch-GL** [comment]
Bonjour Mario,

Voilà un fichier exemple

A+
Pierre Grellet
Chef de projets en informatique technique

De : Mario Baranzini <notifications@github.com>
Envoyé : jeudi, 14 mai 2020 09:45
À : opengisch/OpenComptage <OpenComptage@noreply.github.com>
Cc : Grellet Pierre <Pierre.Grellet@ne.ch>; Mention <mention@noreply.github.com>
Objet : Re: [opengisch/OpenComptage] Manage Marksmann devices data in a different way (#95)


@spch-GL<https://github.com/spch-GL> peux-tu s.v.p. m'envoyer ou joindre ici un fichier d'exemple Marksmann avec la catégorie SWISS7 ?
